- name: Import Elastic GPG Key
  apt_key: url=http://packages.elasticsearch.org/GPG-KEY-elasticsearch state=present
  
- name: Add elasticsearch repository
  apt_repository: repo="deb {{ elasticsearch_install_url }} stable main" state=present update_cache=yes

- name: Install Elasticsearch
  apt: pkg=elasticsearch state=present
#
#- name: Update Elasticsearch configuration
#  template: src=elasticsearch.yml.j2 dest=/etc/elasticsearch/elasticsearch.yml owner=root group=root mode=0644

- name: Set ES_HEAP_SIZE
  lineinfile: >
    dest=/etc/init.d/elasticsearch
    regexp='^export ES_HEAP_SIZE'
    line="export ES_HEAP_SIZE={{ elasticsearch_heap_size }}"
  when: elasticsearch_heap_size is defined
  notify: restart elasticsearch
  ignore_errors: true

- name: Start Elasticsearch
  service: name=elasticsearch state=started